<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DynLoco demo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="demo_files/libs/clipboard/clipboard.min.js"></script>
<script src="demo_files/libs/quarto-html/quarto.js"></script>
<script src="demo_files/libs/quarto-html/popper.min.js"></script>
<script src="demo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="demo_files/libs/quarto-html/anchor.min.js"></script>
<link href="demo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="demo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="demo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="demo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="demo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DynLoco demo</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="perform-short-walks-of-a-range-of-distances" class="level2">
<h2 class="anchored" data-anchor-id="perform-short-walks-of-a-range-of-distances">Perform short walks of a range of distances</h2>
<p>Take walks of varying distances, and show how the optimal trajectory has an inverted-U velocity profile, with peak speed that increases with distance up to about 12 steps. The cost function is total work, plus a linear cost of time with coefficient ctime.</p>
<div class="cell" data-execution_count="1">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DynLoco</span>, <span class="bu">Plots; </span><span class="fu">plotlyjs</span>()</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>wstar4 <span class="op">=</span> <span class="fu">findgait</span>(<span class="fu">WalkRW2l</span>(α<span class="op">=</span><span class="fl">0.35</span>,safety<span class="op">=</span><span class="cn">true</span>), target<span class="op">=:</span>speed<span class="op">=&gt;</span><span class="fl">0.3</span>, varying<span class="op">=:</span>P)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ctime <span class="op">=</span> <span class="fl">0.015</span> <span class="co"># cost of time, to encourage hurrying</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>tchange <span class="op">=</span> <span class="fl">1.75</span> <span class="co"># boundary condition time to get up to speed (arbitrary, excluded from optimization) </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fu">plot</span>() </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>walksteps <span class="op">=</span> [<span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span>, <span class="fl">7</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span>] <span class="co"># take walks of this # of steps</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> <span class="fu">Array</span><span class="dt">{MultiStepResults,1}</span>(<span class="cn">undef</span>,<span class="fl">0</span>) <span class="co"># store each optimization result here</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i,nsteps) <span class="kw">in</span> <span class="fu">enumerate</span>(walksteps)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    result <span class="op">=</span> <span class="fu">optwalktime</span>(wstar4, nsteps, ctime<span class="op">=</span>ctime) <span class="co"># optimize with a cost of time</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plotvees!</span>(result, tchange<span class="op">=</span>tchange, usespline<span class="op">=</span><span class="cn">false</span>, color<span class="op">=</span>i, speedtype<span class="op">=:</span>shortwalks, rampuporder<span class="op">=</span><span class="fl">1</span>, markersize<span class="op">=</span><span class="fl">2</span>) <span class="co"># plot instantaneous body speed vs. time</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">push!</span>(results, result) <span class="co"># add this optimization to results array</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>Plots.<span class="fu">display</span>(p) <span class="co"># instantaneous speed vs. distance profiles</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div style="padding: 1em; background-color: #f8d6da; border: 1px solid #f5c6cb; font-weight: bold;">
<p>The WebIO Jupyter extension was not detected. See the
<a href="https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/" target="_blank">
    WebIO Jupyter integration documentation
</a>
for more information.
</p></div>
<p>Speed vs time for short walks; each trace is a different bout distance</p>
</div>
<div class="cell-output cell-output-display">
<p><img src="demo_files/figure-html/cell-2-output-2.svg" class="img-fluid"></p>
</div>
</div>
</section>
<section id="compare-three-objectives-energy-time-min-cot-constant-accel" class="level2">
<h2 class="anchored" data-anchor-id="compare-three-objectives-energy-time-min-cot-constant-accel">Compare three objectives: Energy-Time, min-COT, constant accel</h2>
<p>Walk a fixed number of steps, starting and ending at rest. The objectives are:</p>
<ul>
<li><strong>Energy-Time</strong> minimizes total energy (positive work) plus proportional time cost</li>
<li><strong>min-COT</strong> minimizes cost of transport (energy per weight and distance traveled)</li>
<li><strong>Constant accel</strong> accelerates at a constant rate, to yield a triangular speed profile. Uses a minimum variance objective to produce a constant rate of velocity change.</li>
</ul>
<p>Compare for a fixed number of steps.</p>
<div class="cell" data-execution_count="2">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Triangle walk, based on min var walk</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>wstar4s <span class="op">=</span> <span class="fu">findgait</span>(<span class="fu">WalkRW2l</span>(α<span class="op">=</span><span class="fl">0.35</span>,safety<span class="op">=</span><span class="cn">true</span>), target<span class="op">=:</span>speed<span class="op">=&gt;</span><span class="fl">0.5</span>, varying<span class="op">=:</span>P)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>wstar4n <span class="op">=</span> <span class="fu">findgait</span>(<span class="fu">WalkRW2l</span>(α<span class="op">=</span><span class="fl">0.35</span>, safety<span class="op">=</span><span class="cn">true</span>), target<span class="op">=:</span>speed<span class="op">=&gt;</span><span class="fl">0.4</span>, varying<span class="op">=:</span>P)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>nsteps <span class="op">=</span> <span class="fl">10</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>ctime <span class="op">=</span> <span class="fl">0.0195</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>tchange <span class="op">=</span> <span class="fl">1.75</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>nominalmsr<span class="op">=</span><span class="fu">optwalktime</span>(wstar4n, nsteps, ctime <span class="op">=</span> ctime, boundarywork<span class="op">=</span><span class="cn">true</span>) <span class="co"># to compare with our usual solution</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>minvarmsr<span class="op">=</span><span class="fu">optwalkvar</span>(wstar4n, nsteps, boundarywork<span class="op">=</span><span class="cn">true</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> <span class="fl">1.9</span><span class="op">*</span>wstar4s.vm<span class="op">/</span>(<span class="fu">nsteps*onestep</span>(wstar4s).tf)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>v0 <span class="op">=</span> <span class="fl">0.11</span><span class="co">#0.8*A*tchange#0.12</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>mintrimsr<span class="op">=</span><span class="fu">optwalktriangle</span>(wstar4n, nsteps, A <span class="op">=</span> A, boundarywork<span class="op">=</span><span class="cn">false</span>,boundaryvels<span class="op">=</span>(v0,v0))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fu">plot</span>(layout<span class="op">=</span>(<span class="fl">1</span>,<span class="fl">2</span>))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plotvees!</span>(p[<span class="fl">1</span>],nominalmsr, tchange<span class="op">=</span>tchange, rampuporder<span class="op">=</span><span class="fl">1</span>, usespline <span class="op">=</span> <span class="cn">false</span>, markershape<span class="op">=:</span>circle,speedtype<span class="op">=:</span>shortwalks)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plotvees!</span>(p[<span class="fl">1</span>],minvarmsr, tchange<span class="op">=</span>tchange, rampuporder<span class="op">=</span><span class="fl">1</span>, usespline <span class="op">=</span> <span class="cn">false</span>,markershape<span class="op">=:</span>circle, speedtype<span class="op">=:</span>shortwalks)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plotvees!</span>(p[<span class="fl">1</span>],mintrimsr, tchange<span class="op">=</span>tchange, rampuporder<span class="op">=</span><span class="fl">1</span>, usespline <span class="op">=</span> <span class="cn">false</span>,markershape<span class="op">=:</span>circle, speedtype<span class="op">=:</span>shortwalks, seriescolor<span class="op">=:</span>auto)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot!</span>(p[<span class="fl">2</span>],[<span class="fl">0</span><span class="op">:</span>nsteps<span class="op">+</span><span class="fl">1</span>], [<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span>; nominalmsr.steps.Pwork; <span class="cn">NaN</span>],markershape<span class="op">=:</span>circle,seriescolor<span class="op">=:</span>auto)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot!</span>(p[<span class="fl">2</span>],[<span class="fl">0</span><span class="op">:</span>nsteps<span class="op">+</span><span class="fl">1</span>], [<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>minvarmsr.vm0<span class="op">^</span><span class="fl">2</span>; minvarmsr.steps.Pwork; <span class="cn">NaN</span>],markershape<span class="op">=:</span>circle,xticks<span class="op">=</span><span class="fl">0</span><span class="op">:</span>nsteps<span class="op">+</span><span class="fl">1</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot!</span>(p[<span class="fl">2</span>],[<span class="fl">0</span><span class="op">:</span>nsteps<span class="op">+</span><span class="fl">1</span>], [<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>mintrimsr.vm0<span class="op">^</span><span class="fl">2</span>; mintrimsr.steps.Pwork; <span class="cn">NaN</span>],markershape<span class="op">=:</span>circle,xticks<span class="op">=</span><span class="fl">0</span><span class="op">:</span>nsteps<span class="op">+</span><span class="fl">1</span>,seriescolor<span class="op">=:</span>auto)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot!</span>(p[<span class="fl">2</span>],xlabel<span class="op">=</span><span class="st">"step"</span>, ylabel<span class="op">=</span><span class="st">"push-off work"</span>, legend<span class="op">=</span><span class="cn">false</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>energytimework <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(nominalmsr.steps.Pwork)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>mincotwork <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>minvarmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(minvarmsr.steps.Pwork)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>trianglework <span class="op">=</span> (<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>mintrimsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(mintrimsr.steps.Pwork))<span class="op">/</span>(<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(nominalmsr.steps.Pwork))</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>Plots.<span class="fu">display</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="demo_files/figure-html/cell-3-output-1.svg" class="img-fluid"></p>
</div>
</div>
<p>Quantify the three predictions.</p>
<div class="cell" data-execution_count="3">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Markdown</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"energy-time work = "</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(nominalmsr.steps.Pwork))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"min-COT = "</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>minvarmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(minvarmsr.steps.Pwork))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"triangle   = "</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>mintrimsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(mintrimsr.steps.Pwork))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"ratio = "</span>,  (<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>minvarmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(minvarmsr.steps.Pwork))<span class="op">/</span>(<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(nominalmsr.steps.Pwork)) )</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"ratio = "</span>,  (<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>mintrimsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(mintrimsr.steps.Pwork))<span class="op">/</span>(<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(nominalmsr.steps.Pwork)) )</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#println("ratio = ",  (sum(minvarmsr.steps.Pwork))/(sum(nominalmsr.steps.Pwork)) )</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>threecosts <span class="op">=</span> [<span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>nominalmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(nominalmsr.steps.Pwork), <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>minvarmsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(minvarmsr.steps.Pwork), <span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">*</span>mintrimsr.vm0<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu">sum</span>(mintrimsr.steps.Pwork)]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">bar</span>(threecosts,xticks<span class="op">=</span>((<span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">3</span>),(<span class="st">"Energy-Time"</span>, <span class="st">"Steady min-COT"</span>, <span class="st">"Steady accel"</span>)),legend<span class="op">=</span><span class="cn">false</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>energy-time work = 0.21077394712113307
min-COT = 0.23455721768541665
triangle   = 0.2753143264615154
ratio = 1.1128378098390652
ratio = 1.3062066266818573</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<p><img src="demo_files/figure-html/cell-4-output-2.svg" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="4">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Markdown</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Markdown.<span class="fu">parse</span>(<span class="st">"""</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="st">The energy-time work is </span><span class="sc">$</span>(threecosts[<span class="fl">1</span>])<span class="st">. </span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="st">The min-COT work is </span><span class="sc">$</span>(threecosts[<span class="fl">2</span>])<span class="st">.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="st">The const accel work is </span><span class="sc">$</span>(threecosts[<span class="fl">3</span>])<span class="st">.</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<p>The energy-time work is 0.21077394712113307. The min-COT work is 0.23455721768541665. The const accel work is 0.2753143264615154.</p>
</div>
</div>
</section>
<section id="brachistokuo-ramp" class="level2">
<h2 class="anchored" data-anchor-id="brachistokuo-ramp">Brachistokuo ramp</h2>
<p>Optimal slope and walk with ramp, compared with flat walking in same amount of time. We find six steps to be pretty good. Longer walks yield a smaller differene because there’s more time spent at a steady speed. Note: Currently solving for an asymmetric ramp profile, because pure symmetry constraint is slightly overconstrained for latest Ipopt.</p>
<div class="cell" data-execution_count="5">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>wstar <span class="op">=</span> <span class="fu">findgait</span>(<span class="fu">WalkRW2l</span>(α<span class="op">=</span><span class="fl">0.35</span>,safety<span class="op">=</span><span class="cn">true</span>), target<span class="op">=:</span>speed<span class="op">=&gt;</span><span class="fl">0.4</span>, varying<span class="op">=:</span>P)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="fl">6</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>walktime <span class="op">=</span> N <span class="op">*</span> <span class="fu">onestep</span>(wstar).tf <span class="op">*</span><span class="fl">0.82</span> <span class="co"># meant to be a brisk walk</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>walkdistance <span class="op">=</span> N <span class="op">*</span> <span class="fu">onestep</span>(wstar).steplength</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>rampresult <span class="op">=</span> <span class="fu">optwalkslope</span>(wstar, N, boundaryvels <span class="op">=</span> (<span class="fl">0</span>., <span class="fl">0</span>.), symmetric <span class="op">=</span> <span class="cn">false</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    totaltime <span class="op">=</span> walktime)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fu">multistepplot</span>(rampresult; plotwork<span class="op">=</span><span class="cn">true</span>, label<span class="op">=</span><span class="st">"ramp"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"ramp total cost = "</span>, rampresult.totalcost)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>flatresult <span class="op">=</span> <span class="fu">optwalk</span>(wstar, N, boundaryvels <span class="op">=</span> (<span class="fl">0</span>., <span class="fl">0</span>.),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    totaltime <span class="op">=</span> rampresult.totaltime, δs <span class="op">=</span> <span class="fu">zeros</span>(<span class="fl">6</span>))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"flat total cost = "</span>, flatresult.totalcost)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="fu">multistepplot!</span>(flatresult; plotwork<span class="op">=</span><span class="cn">true</span>, label<span class="op">=</span><span class="st">"flat"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># optionally, try a reversed ramp and see if it's higher cost still</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">#concaveresult = optwalk(wstar, 6, boundaryvels = (0.,0.), boundarywork=true,</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">#    totaltime = rampresult.totaltime, δ = -rampresult.δangles)</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co">#multistepplot!(concaveresult; plotwork=true)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>ramp total cost = 0.1870530240274279
flat total cost = </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>0.21330138986318115</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<p><img src="demo_files/figure-html/cell-6-output-3.svg" class="img-fluid"></p>
</div>
</div>
<section id="brachistokuo-ramp-compute-the-cost-for-different-speeds" class="level3">
<h3 class="anchored" data-anchor-id="brachistokuo-ramp-compute-the-cost-for-different-speeds">Brachistokuo ramp: Compute the cost for different speeds</h3>
<div class="cell" data-execution_count="6">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>walktimes <span class="op">=</span> (<span class="fl">0.8</span><span class="op">:</span><span class="fl">0.05</span><span class="op">:</span><span class="fl">1.2</span>) <span class="op">*</span> <span class="fu">N*onestep</span>(wstar).tf</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>rampresults <span class="op">=</span> <span class="fu">Array</span><span class="dt">{MultiStepResults,1}</span>(<span class="cn">undef</span>, <span class="fu">length</span>(walktimes))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>flatresults <span class="op">=</span> <span class="fu">Array</span><span class="dt">{MultiStepResults,1}</span>(<span class="cn">undef</span>, <span class="fu">length</span>(walktimes))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i,walktime) <span class="kw">in</span> <span class="fu">enumerate</span>(walktimes)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    rampresults[i] <span class="op">=</span> <span class="fu">optwalk</span>(wstar, N, boundaryvels <span class="op">=</span> (<span class="fl">0</span>.,<span class="fl">0</span>.),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        totaltime <span class="op">=</span> walktime, δs <span class="op">=</span> rampresult.δangles)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    flatresults[i] <span class="op">=</span> <span class="fu">optwalk</span>(wstar, N, boundaryvels <span class="op">=</span> (<span class="fl">0</span>.,<span class="fl">0</span>.),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        totaltime <span class="op">=</span> walktime, δs <span class="op">=</span> <span class="fu">zeros</span>(N))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot totalcost vs average speed</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(walkdistance <span class="op">./</span> walktimes, [<span class="fu">getfield</span>.(rampresults, <span class="op">:</span>totalcost), <span class="fu">getfield</span>.(flatresults, <span class="op">:</span>totalcost)],</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    xlabel<span class="op">=</span><span class="st">"Average speed"</span>, ylabel<span class="op">=</span><span class="st">"Total Work"</span>, labels<span class="op">=</span>[<span class="st">"Ramp"</span> <span class="st">"Flat"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<p><img src="demo_files/figure-html/cell-7-output-1.svg" class="img-fluid"></p>
</div>
</div>
</section>
<section id="plot-the-ramp-to-scale" class="level3">
<h3 class="anchored" data-anchor-id="plot-the-ramp-to-scale">Plot the ramp to scale</h3>
<div class="cell" data-execution_count="7">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">onestep</span>(wstar).steplength <span class="op">.*</span> (<span class="fl">0</span><span class="op">:</span><span class="fl">6</span>),<span class="fu">cumsum</span>(<span class="fu">tan</span>.([<span class="fl">0</span>;rampresult.δangles])<span class="op">.*</span><span class="fu">onestep</span>(wstar).steplength),</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    aspect_ratio<span class="op">=</span><span class="fl">1</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sl <span class="op">=</span> <span class="fu">onestep</span>(wstar).steplength</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sl <span class="op">.*</span> [<span class="fl">0</span>; <span class="fu">cumsum</span>(<span class="fu">cos</span>.(rampresult.δangles))],[<span class="fl">0</span>; <span class="fu">cumsum</span>(<span class="fu">sin</span>.(rampresult.δangles))]<span class="op">.*</span>sl,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    aspect_ratio<span class="op">=</span><span class="fl">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<p><img src="demo_files/figure-html/cell-8-output-1.svg" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="short-walks-of-varying-slope" class="level2">
<h2 class="anchored" data-anchor-id="short-walks-of-varying-slope">Short walks of varying slope</h2>
<p>To be compared with Emily’s data</p>
<div class="cell" data-execution_count="8">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>wstar4s <span class="op">=</span> <span class="fu">findgait</span>(<span class="fu">WalkRW2l</span>(α<span class="op">=</span><span class="fl">0.4</span>,safety<span class="op">=</span><span class="cn">true</span>), target<span class="op">=:</span>speed<span class="op">=&gt;</span><span class="fl">0.4</span>, varying<span class="op">=:</span>P)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>myslopes <span class="op">=</span> <span class="fl">0</span><span class="op">:</span><span class="fl">0.02</span><span class="op">:</span><span class="fl">0.08</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fu">plot</span>(layout<span class="op">=</span>(<span class="fl">2</span>,<span class="fl">1</span>))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>nsteps <span class="op">=</span> <span class="fl">6</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>startv <span class="op">=</span> wstar4.vm</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> slope <span class="kw">in</span> myslopes</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># walk up a slope</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    resultup <span class="op">=</span> <span class="fu">optwalktime</span>(wstar4s, nsteps, ctime <span class="op">=</span> ctime, δs<span class="op">=</span><span class="fu">fill</span>(slope, nsteps))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plotvees!</span>(p[<span class="fl">1</span>],resultup, tchange<span class="op">=</span><span class="fl">1</span>, title<span class="op">=</span><span class="st">"Up"</span>, rampuporder<span class="op">=</span><span class="fl">1</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    startv <span class="op">=</span> [resultup.vm0;resultup.steps.vm]</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Walk down a slope</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    resultdown <span class="op">=</span> <span class="fu">optwalktime</span>(wstar4s, nsteps, ctime <span class="op">=</span> ctime, δs<span class="op">=</span><span class="fu">fill</span>(<span class="op">-</span>slope, nsteps))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plotvees!</span>(p[<span class="fl">2</span>],resultdown, tchange<span class="op">=</span><span class="fl">1</span>, title<span class="op">=</span><span class="st">"Down"</span>, rampuporder<span class="op">=</span><span class="fl">1</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>Plots.<span class="fu">display</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>times </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.0, 2.442996751011905, 4.43492795426176, 6.3285530856496734, 8.221830737800136, 10.212322734043118, 12.649534456102629, 13.649534456102629]
v = [0.0, 0.31880381514821987, 0.39099577502808397, 0.4112940157519249, 0.4113695018438875, 0.39127848094206935, 0.31956053615201, 0.0]
3.3697605293837327</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> 14.205090011658186 2.9329674287413514
times [0.0, 2.442996751011905, 4.43492795426176, 6.3285530856496734, 8.221830737800136, 10.212322734043118, 12.649534456102629, 13.649534456102629]
v = [0.0, 0.31880381514821987, 0.39099577502808397, 0.4112940157519249, 0.4113695018438875, 0.39127848094206935, 0.31956053615201, 0.0]
3.3697605293837327 14.205090011658186 2.9329674287413514
times [0.0, 2.332949074464901, 4.296874719473847, 6.175963486654021, 8.061944957439469, 10.056925731019561, 12.577071236657874, 13.577071236657874]
v = [0.0, 0.3338421284639227, 0.3965713705081505, 0.41447572792745174, 0.4129609419189796, 0.39039809051374436, 0.3090443321128929, 0.0]
2.6361085644425932 14.132626792213431 3.636108564442594
times </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.0, 2.527199585244839, 4.523877806523506, 6.41032790942487, 8.289179620574764, 10.25188800146023, 12.580119703048876, 13.580119703048876]
v = [0.0, 0.3081817079919496, 0.3900661991087056, 0.41285835412208816, 0.41452802261900584, 0.3968173225336374, 0.33451854645131324, 0.0]
3.351493489106429 14.135675258604433 2.922007204574969
times [0.0, 2.201298980646913, 4.114349358571499, 5.957931998555288, 7.8160866685070545, 9.794043380695129, 12.371747668313947, 13.371747668313947]
v = [0.0, 0.3538077705321147, 0.4071177077219674, 0.42245824392453046, 0.41914523974342655, 0.3937582050295373, 0.30214353460099946, 0.0]
2.5928825500543984 13.927303223869504 3.5928825500543997
times [0.0, 2.585942002177281, 4.565705378865095, 6.424283685236989, 8.26754630661788, 10.179355543863437, 12.376464617148025, 13.376464617148025]
v = [0.0, 0.30118103343444874, 0.3933988747283079, 0.4190497015633729, 0.4225315891415576, 0.40738200728615154, 0.35448248522908876, 0.0]
3.890813387871306 13.709797950481358 2.0747155737348795
times [0.0, 2.0576806206836293, 3.900372015034872, 5.690270558236855, 7.502885917794261, 9.445365947111993, 12.058322642833854, 13.058322642833854]
v = [0.0, 0.3785022207958327, 0.4226625722596955, 0.4351289560938049, 0.4296756509927581, 0.40094964831677393, 0.2980671994650633, 0.0]
1.8396181950673336 13.613878198389411 3.526898334163853
times </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[0.0, 2.622112937640853, 4.566226914836328, 6.378926798267447, 8.168094708725883, 10.00911720674641, 12.062424500255128, 13.062424500255128]
v = [0.0, 0.2970263688634365, 0.4006126666199012, 0.42965561576751565, 0.4353066473329159, 0.4230457180478286, 0.37930839045840775, 0.0]
3.7916428246419698 13.39575783358846 2.041658719325101
times [0.0, 1.91395131605842, 3.673214655664929, 5.396074540839549, 7.149730090869841, 9.042337217592388, 11.672297637675179, 12.672297637675179]
v = [0.0, 0.40692606864276604, 0.44270614130542957, 0.45206037433413365, 0.4441218143459514, 0.41151524456426575, 0.2961400782574453, 0.0]
1.1117038449014807 13.227853193230736 4.112592945587036
times [0.0, 2.639684003270013, 4.533414858539329, 6.28648636989119, 8.0078566729253, 9.764622695231052, 11.673471283143257, 12.673471283143257]
v = [0.0, 0.29504921181947774, 0.41127105388296553, 0.4442697742642057, 0.45245156329495956, 0.4433354668341542, 0.4080138621519217, 0.0]
3.6688154929224317 13.00680461647659 1.333691471042627</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="demo_files/figure-html/cell-9-output-6.svg" class="img-fluid"></p>
</div>
</div>
</section>
<section id="todo-uneven-terrain" class="level2">
<h2 class="anchored" data-anchor-id="todo-uneven-terrain">Todo: Uneven terrain</h2>
<ol type="1">
<li>Plot uneven terrain profile</li>
<li>Draw a stick figure model (see Matlab walkrw2 animation)</li>
<li>Generate automatic superposition figure</li>
</ol>
</section>
<section id="todo-short-walks" class="level2">
<h2 class="anchored" data-anchor-id="todo-short-walks">Todo: Short walks</h2>
<ol type="1">
<li>Analyze ramp data (from Emily)</li>
<li>Analyze different speed data</li>
</ol>
</section>
<section id="step-to-step-transitions-and-energy-cost" class="level2">
<h2 class="anchored" data-anchor-id="step-to-step-transitions-and-energy-cost">Step-to-step transitions and energy cost</h2>
<ol type="1">
<li>Metabolic power for preferred walking</li>
<li>Inverse dynamics grid data for COM power, work</li>
<li>Edot = v^3.42 plot</li>
</ol>
</section>
<section id="todo-mechanics-story" class="level2">
<h2 class="anchored" data-anchor-id="todo-mechanics-story">Todo: Mechanics story</h2>
<ol type="1">
<li>Some nice figures to show energy-time-slope tradeoff</li>
<li>Step-to-step transition through prediction</li>
</ol>
</section>
<section id="todo-photos-video-of-brachistokuo" class="level2">
<h2 class="anchored" data-anchor-id="todo-photos-video-of-brachistokuo">Todo: Photos &amp; video of brachistokuo</h2>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>